import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import ClientPortal from "../components/ClientPortal";
import Nav from "../components/layout/Nav";
import MobileMenu from "../components/common/MobileMenu";
import HeroSection from "../components/landing/Hero";
import ServicesSection from "../components/landing/Services";
import ArticlesSection from "../components/landing/Articles";
import Footer from "./../components/layout/Footer";

export default function Home() {
  const [showMenu, setShowMenu] = useState(false);

  return (
    <>
      <Head>
        <title>Easy Bank</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap'
          rel='stylesheet'
        />
      </Head>
      <Nav
        show={showMenu}
        onOpen={() => setShowMenu(true)}
        onClose={() => setShowMenu(false)}
      />

      <MobileMenu show={showMenu} onClose={() => setShowMenu(false)} />

      <HeroSection />
      <ServicesSection />
      <ArticlesSection />
      <Footer />
    </>
  );
}
